config/routes.rb
# -*- coding: utf-8 -*-
Rails.application.routes.draw do

  devise_for :users, :path => "/", :skip => [:confirmations],
    :controllers => {:sessions => "sessions", :passwords => "passwords", :registrations => "registrations", :sign_up => 'no_sign_up',},
    :path_names => {:sign_in => 'login', :sign_out => 'logout', :registration => "profile"}

  root :to => 'tops#show'
  resource :top, :only => [:show]

  get  'operative_settings/control_panel', to: 'operative_settings#control_panel'
  post 'operative_settings/control_panel', to: 'operative_settings#control_panel'

  resource :security_policy, :except => [:destroy] do
    post :change_status, :on => :member
  end
  resource :accounts_setting, :except => [:destroy] do
    post :change_status, :on => :member
  end

  get '/company_banks/search_bank', to: 'company_banks#search_bank'
  get '/company_banks/search_branch', to: 'company_banks#search_branch'
  resources :company_banks

  resource :date_bank_payment
  resource :date_bank_settlement
  resource :payment_notice

  resources :receivables do
    get :search_bank, on: :collection
    get :search_branch, on: :collection
    get :make_modal, on: :collection
    get :search, on: :collection
    get :result, on: :collection
  end
  namespace :receivables do
    resources :settlements do
      get :search, on: :collection
      get :result, on: :collection
      post :select, on: :collection
      post :confirm, on: :collection
      post :update_all, on: :collection
    end
  end
  # FIXME: 検索にreceivableを利用するようになれば削除
  resources :receivable_searches, :only => [:index]

  namespace :receivables do
    resources :discounts do
      get :search, on: :collection
      get :result, on: :collection
      post :select, on: :collection
      post :confirm, on: :collection
      post :update_all, on: :collection
    end
    resources :transfers do
      get :select, on: :collection
      post :search, on: :collection
      get :result, on: :collection
      post :confirm, on: :collection
      post :update_all, on: :collection
      get :trader_search, on: :collection
      get :company_bank_search, on: :collection
    end
    get "dealing_choice/regist", :to => "dealing_choice#regist"
    get "dealing_choice/discounts", :to => "dealing_choice#discounts"
    get "dealing_choice/transfers", :to => "dealing_choice#transfers"
  end

  namespace :journals do
    resources :dealing_choice do
      get :select, on: :collection
    end
    resources :journal_data do
      get :search, on: :collection
      get :confirm, on: :collection
      post :output, on: :collection
    end
  end

  resources :payables
  resources :departments
  resources :approval_settings, :except => [:destroy, :create]
  resources :remarks
  resources :users
  resources :license_allotments
  resources :abridgments
  resources :management_items
  get '/menu_authorities/menu_option_collections'
  resources :menu_authorities
  get '/approvers/menu_collection'

  resources :approvers
  resources :traders do
    get :edit_or_delete, on: :collection
    get :site, on: :collection
    get :search, on: :collection
  end
  resources :traders
  resources :slip_divisions
  resources :accounts
  resources :sub_accounts
  resources :analysis_divisions
  resources :analysis_items
  resources :operating_divisions
  resources :operating_division_settings
  resources :operating_items
  resources :receipts
  resources :date_bank_spreadsheets

  get 'default_payable_sites/make_trader_site_modal', to: 'default_payable_sites#make_trader_site_modal'
  get  'default_payable_sites', to: 'default_payable_sites#index'
  post 'default_payable_sites', to: 'default_payable_sites#update'

  get 'date_bank_choice', to: 'date_bank_choice#index'

  resources :use_accounts

  namespace :admin do
    devise_for :administrators, :path => "/", :skip => [:confirmations],
      :path_names => {:sign_in => 'login', :sign_out => 'logout', :registration => "profile", :sign_up => 'no_sign_up'}

    root :to => 'tops#show'
    resource :top, only: [:show]
    resources :products
    resources :management_divisions
    resources :companies do
      resource :user
      resources :licenses
    end
    resources :recording_institutions
    resources :banks, only: [:new, :create]
    get '/financial_institutions', :to => 'financial_institutions#index'
    post '/financial_institutions/import', :to => 'financial_institutions#import'
    resource  :banks
    resources :branches
    resources :menus
    resources :state_codes
    resources :administrators
    resources :recording_institutions
    resources :business_divisions
    resources :bank_holidays
    resources :stamp_taxes
    resources :tax_divisions
    resources :tax_rates
    resources :infos
  end

end

app/controllers/receivables/dealing_choice_controller.rb
class Receivables::DealingChoiceController < BaseController

  def regist
  end

  def discounts
  end

  def transfers
  end
end

app/controllers/receivables/discounts_controller.rb
class Receivables::DiscountsController < BaseController
  def search
    if params[:back]
      # 戻る押下時
      @q = ReceivableSearch.search(session[:search_condition])
      @aggregate_scope = session[:aggregate_scope]
    else
      @q = ReceivableSearch.search
      # 検索条件をsessionから削除
      session[:search_condition] = nil
      session[:aggregate_scope] = nil
    end
  end

  def result
    if params[:back]
      # 戻る押下時
      @select_ids = session[:select_ids]
    else
      # 検索条件をsessionに保持
      session[:search_condition] = search_params.merge(search_query)
      session[:aggregate_scope] = set_request_param
      # 選択したidをsessionから削除
      session[:select_ids] = nil
    end
    @q = ReceivableSearch.search(session[:search_condition])
    @receivable_searches = @q.result(distinct: true)
    @search_institution_bank = recording_institution_bank
  end

  def select
    if params[:back]
      # 戻る押下時
      @input_params = session[:input_params]
    else
      # 選択したidをsessionに保持
      session[:select_ids] = select_params
      # 入力した割引日付と手数料をsessionから削除
      session[:input_params] = nil
    end
    @q = ReceivableSearch.search(session[:select_ids])
    @receivable_searches = @q.result(distinct: true)
    @search_institution_bank = recording_institution_bank
  end
  def confirm
    @q = ReceivableSearch.search(session[:select_ids])
    @receivable_searches = @q.result(distinct: true)
    @search_institution_bank = recording_institution_bank
    # 入力した割引日付と手数料をsessionに保持
    session[:input_params] = input_params
    @input_params = session[:input_params]
  end
  def update_all
  end
  private
  def search_params
    submit_params = params.require(:q).permit(
      :state_code_id_eq,
      :recording_institution_id_eq,
      :company_bank_id_eq,
      :trader_id_gteq,
      :trader_id_lteq,
      :residual_money_gteq,
      :residual_money_lteq,
      :company_bank_id_gteq,
      :discount_requested_on_gteq,
      :discount_requested_on_lteq,
      :transferred_on_gteq,
      :transferred_on_lteq
    )
  end
  def set_request_param
    param_hash = Hash.new()
    param_hash[:period_type_1] = params[:period_type_1]
    param_hash[:period_type_2] = params[:period_type_2]
    param_hash[:period_1_from] = params[:period_1_from]
    param_hash[:period_2_from] = params[:period_2_from]
    param_hash[:period_1_to] = params[:period_1_to]
    param_hash[:period_2_to] = params[:period_2_to]

    param_hash
  end
  def search_query
    receivable_search = ReceivableSearch.new(set_request_param)
    receivable_search.receivable_search
  end
  def select_params
    select_params = params.require(:q).permit(id_eq_any: [])
  end
  def input_params
    input_params = params.require(:discount).permit(
      :requested_on,
      :transferred_on,
      discount_charge: [],
      bank_transfer_fee: [],
      id: [])
  end

  def recording_institution_bank
    return_param = Hash.new
    return_param[:recording_institution] = RecordingInstitution.where(code: session[:search_condition]['recording_institution_id_eq']).pluck(:abbreviation).first
    return_param[:bank] = CompanyBank.where(code: session[:search_condition]['company_bank_id_eq']).pluck(:code, :name, :bank_code, :bank_name, :branch_code, :branch_kana, :account_type, :account_number).first
    return_param[:bank][6] = t(Settings.enumerize_options.company_bank.account_types.select{|at| at.id == return_param[:bank][6].to_i}.first[:name])
    return_param
  end
end

app/controllers/receivables/settlements_controller.rb
class Receivables::SettlementsController < BaseController

  def new
  end

  def create
  end

  def search
    if params[:back]
      @q = ReceivableSearch.search(session[:search_condition])
      @aggregate_scope = session[:aggregate_scope]

    else
      # 戻る押下時
      @q = ReceivableSearch.search
      # 検索条件をsessionから削除
      session[:search_condition] = nil
      session[:aggregate_scope] = nil
    end
  end

  def result
    if params[:back]
      # 戻る押下時
      @select_ids = session[:select_ids]
    else
      # 検索条件をsessionに保持
      session[:search_condition] = search_query(search_params)
      session[:aggregate_scope] = set_request_param
      # 選択したidをsessionから削除
      session[:select_ids] = nil
    end
    @q = ReceivableSearch.search(session[:search_condition])
    @receivable_searches = @q.result(distinct: true)
  end

  def select
    unless params[:back]
      # 選択したidをsessionに保持
      session[:select_ids] = select_params
      # 入力した手数料をsessionから削除
      session[:input_params] = {}
      session[:receivable_searches] = nil
    end
    @q = ReceivableSearch.search(session[:select_ids])
    @receivable_searches = @q.result(distinct: true)
    @input_params = session[:input_params]
  end

  def confirm
    @q = ReceivableSearch.search(session[:select_ids])
    @receivable_searches = @q.result(distinct: true)
    # 入力した手数料をsessionに保持
    session[:input_params] = input_params

    input_params_zip = input_params[:id].zip(input_params[:fee])
    @receivable_searches.each {|item|
      input_params_zip.each{|elem|
        if item.id == elem.first.to_i
          item.bank_transfer_fee = elem.last.to_i
        end
      }
    }
    @input_params = session[:input_params]
    session[:receivable_searches] = @receivable_searches
  end

  def update_all
  end

  private
  def search_params
    submit_params = params.require(:q).permit(
      :settled_on_gteq,
      :settled_on_lteq,
      :trader_id_gteq,
      :trader_id_lteq,
      :residual_money_gteq,
      :residual_money_lteq,
      :company_bank_id_gteq,
      :company_bank_id_lteq,
      :recording_institution_id_eq,
      :recording_number_gteq,
      :recording_number_lteq,
      :acquisition_division_eq_any,
      :name_specified,
      :name_specified_words,
      :their_particulars,
      state_code_id_eq_any: []
    )
  end

  def search_query(args_param)
    # パラメータのセット
    hash_param = set_request_param
    # 検索クエリの作成
    receivable_search = ReceivableSearch.new(hash_param)
    settlement_query = receivable_search.settlement_search

    args_param.merge(settlement_query)
  end

  def set_request_param
    param_hash = Hash.new()

    param_hash[:cancel_flag] = params[:cancel_flag]
    param_hash[:recording_institutions_check] = params[:recording_institutions_check]
    param_hash[:period_type_1] = params[:period_type_1]
    param_hash[:period_type_2] = params[:period_type_2]
    param_hash[:period_1_from] = params[:period_1_from]
    param_hash[:period_2_from] = params[:period_2_from]
    param_hash[:period_1_to] = params[:period_1_to]
    param_hash[:period_2_to] = params[:period_2_to]

    param_hash
  end
  def select_params
    select_params = params.require(:q).permit(id_eq_any: [])
  end
  def input_params
    input_params = params.require(:settlement).permit(
      fee: [],
      id: [])
  end
end

app/controllers/receivables/transfers_controller.rb
class Receivables::TransfersController < BaseController

  def select
    if params[:back]
      # 戻る押下時
      @instance = Transfer.new(session[:transfer_params])
    else
      @instance = Transfer.new
      @instance.trader = Transfer::Trader.new
      @instance.company_bank = Transfer::CompanyBank.new
      session[:transfer_params] = nil
      session[:recording_institution] = nil
      session[:own_bank] = nil
      session[:transferee_bank] = nil
    end
  end
  def trader_search
    trader = Trader.where(code: params[:trader_code]).first
    trader_bank = TraderBankAccount.where(trader_id: trader.try(:id)).first
    @json = {name: trader.try(:name1),
             kana: trader.try(:kana),
             bank_code: trader_bank.try(:bank_code),
             branch_code: trader_bank.try(:branch_code),
             account_type: trader_bank.try(:account_type),
             account_number: trader_bank.try(:account_number),
             user_number: trader_bank.try(:ebill_user_number)}
    render json: @json.to_json and return if request.xhr?
  end
  def company_bank_search
    company_bank = CompanyBank.where(company_id: current_user.company_id, code: params[:company_bank_code]).first
    @json = {name: company_bank.try(:name),
             kana: company_bank.try(:account_name_kana),
             bank_code: company_bank.try(:bank_code),
             branch_code: company_bank.try(:branch_code),
             account_type: company_bank.try(:account_type),
             account_number: company_bank.try(:account_number),
             user_number: company_bank.try(:user_number)}
    render json: @json.to_json and return if request.xhr?
  end
  def search
    if params[:back]
      # 戻る押下時
      @q = ReceivableSearch.search(session[:search_condition])
      @aggregate_scope = session[:aggregate_scope]
    else
      @q = ReceivableSearch.search
      @instance = Transfer.new(transfer_params)
      # 検索条件をsessionから削除
      session[:search_condition] = nil
      session[:aggregate_scope] = nil
      # 入力した値をsessionに保持
      session[:transfer_params] = transfer_params
      # 記録機関を設定
      session[:recording_institution] = recording_institution
      # 自社取引銀行を設定
      session[:own_bank] = own_bank
      # 譲渡先銀行を設定
      session[:transferee_bank] = transferee_bank
    end
    @instance = Transfer.new(session[:transfer_params])
    @recording_institution = session[:recording_institution]
    @own_bank = session[:own_bank]
    @transferee_bank = session[:transferee_bank]
  end
  def result
    if params[:back]
      # 戻る押下時
      @select_ids = session[:select_ids]
    else
      # 検索条件をsessionに保持
      session[:search_condition] = search_params.merge(search_query)
      session[:aggregate_scope] = set_request_param
      # 選択したidをsessionから削除
      session[:select_ids] = nil
    end
    @instance = Transfer.new(session[:transfer_params])
    @recording_institution = session[:recording_institution]
    @own_bank = session[:own_bank]
    @transferee_bank = session[:transferee_bank]
    @q = ReceivableSearch.search(session[:search_condition])
    @receivable_searches = @q.result(distinct: true)
  end
  def confirm
    @q = ReceivableSearch.search(select_params)
    session[:select_ids] = select_params
    @receivable_searches = @q.result(distinct: true)
    @instance = Transfer.new(session[:transfer_params])
    @recording_institution = session[:recording_institution]
    @own_bank = session[:own_bank]
    @transferee_bank = session[:transferee_bank]
  end
  private
  def transfer_params
    params.require(:transfer).permit(
      :recording_institution_id,
      :trader_id,
      :transferred_on,
      :company_bank_id,
      :guaranteed,
      trader_attributes: [:name, :kana, :bank_code, :branch_code, :account_type, :account_number, :user_number],
      company_bank_attributes: [:code]
    )
  end
  def search_params
    submit_params = params.require(:q).permit(
      :state_code_id_eq,
      :recording_institution_id_eq,
      :company_bank_id_eq,
      :trader_id_gteq,
      :trader_id_lteq,
      :residual_money_gteq,
      :residual_money_lteq,
      :transferred_on_gteq,
      :transferred_on_lteq,
      :transferee_trader_id_gteq,
      :transferee_trader_id_lteq
    )
  end
  def set_request_param
    param_hash = Hash.new()
    param_hash[:period_type_1] = params[:period_type_1]
    param_hash[:period_type_2] = params[:period_type_2]
    param_hash[:period_1_from] = params[:period_1_from]
    param_hash[:period_2_from] = params[:period_2_from]
    param_hash[:period_1_to] = params[:period_1_to]
    param_hash[:period_2_to] = params[:period_2_to]

    param_hash
  end
  def search_query
    receivable_search = ReceivableSearch.new(set_request_param)
    receivable_search.receivable_search
  end
  def select_params
    select_params = params.require(:q).permit(id_eq_any: [])
  end
  # 記録機関検索
  def recording_institution
    RecordingInstitution.where(code: @instance.recording_institution_id).pluck(:abbreviation).first
  end
  # 自社取引銀行検索
  def own_bank
    CompanyBank.where(code: @instance.company_bank_id).pluck(:bank_name, :branch_name, :bank_code, :branch_code, :account_type, :account_number).first
  end
  # 取引先銀行検索
  def transferee_bank
    transferee_bank = Bank.where(code: @instance.trader.bank_code).pluck(:id, :name).first
    branch_name = Branch.where(bank_id: transferee_bank.fetch(0, nil), code: @instance.trader.branch_code).pluck(:name).first
    {bank_name: transferee_bank[1], branch_name: branch_name}
  end
end

app/helpers/receivables/dealing_choice_helper.rb
module Receivables::DealingChoiceHelper
end

app/helpers/receivables/discounts_helper.rb
module Receivables::DiscountsHelper
end

app/helpers/receivables/settlements_helper.rb
module Receivables::SettlementsHelper
end

app/helpers/receivables/transfers_helper.rb
module Receivables::TransfersHelper
end

app/helpers/receivables_helper.rb
module ReceivablesHelper
end

app/views/receivables/transfers/confirm.html.slim
= render :partial => 'shared/receivables/stage'
section.container
  = form_tag result_receivables_transfers_path, method: :get do
    .row
      = submit_tag '戻る', name: :back, class: "btn btn-default col-xs-2 pull-right back-button"

  div
    .financial-institutions
      = render partial: "search_information"
    .row.transfer_amount
      .col-xs-2
        label = '譲渡金額合計'
      .col-xs-10
        = "#{number_to_currency(total_amount = @receivable_searches.inject(0) { |sum, r| sum + r.residual_money }, unit: '', precision: 0)}円"

    .result_container
      .row
        = form_tag update_all_receivables_transfers_path do
          .row.text-center
            .col-xs-1 No
            .col-xs-2 記録番号
            .col-xs-1 支払期日
            .col-xs-2 譲渡金額
            .col-xs-2 請求先
            .col-xs-2 債務者
            .col-xs-1 発生日
            .col-xs-1 譲受日

          - @receivable_searches.each_with_index do |r, i|
            .row
              .col-xs-1.text-center = "No#{i+1}"
              .col-xs-2 = r.recording_number
              .col-xs-1 = r.try(:matured_on).try(:strftime, "%Y-%m-%d")
              .col-xs-2.text-right = number_to_currency(r.try(:residual_money), unit: '', precision: 0)
              .col-xs-2 = r.trader.try(:abbreviation)
              .col-xs-2 = r.try(:debtor_name)
              .col-xs-1 = r.try(:occurred_on).try(:strftime, "%Y-%m-%d")
              .col-xs-1 = r.try(:transferred_on).try(:strftime, "%Y-%m-%d")
          .row
            actions.col-xs-12
              = submit_tag '一括更新', class: 'btn btn-primary col-xs-2 col-xs-offset-10'

app/views/receivables/transfers/result.html.slim
= render :partial => 'shared/receivables/stage'
section.container
  .row
    = form_tag search_receivables_transfers_path do
      = submit_tag '戻る', name: :back, class: "btn btn-default col-xs-2 pull-right back-button"

  div
    = render partial: "search_information"
    .row
      .col-xs-1.col-xs-offset-8
        label = '支払金額'
      = text_field_tag :payment_amount, nil, class: 'col-xs-2 money_format text-right'
      = t('general.misc.yen')
    .row
      .col-xs-2.col-xs-offset-4
        label = '指定件数'
      .col-xs-2#select_number
        = '0件'
      .col-xs-1
        label = '指定金額'
      .col-xs-2#select_amount.text-right
      .col-xs-1.killpadding
        = t('general.misc.yen')
  .result_container
    .row.text-center
      .col-xs-1 No
      .col-xs-1 選択
      .col-xs-2 記録番号
      .col-xs-1 支払期日
      .col-xs-1 債権残高
      .col-xs-1 原債権金額
      .col-xs-2 請求先
      .col-xs-1 債務者
      .col-xs-1 発生日
      .col-xs-1 譲受日

    = search_form_for @q, url: confirm_receivables_transfers_path, method: :post do |f|
      - @receivable_searches.each_with_index do |r, i|
        .row
          .col-xs-1.text-center = "No#{i+1}"
          .col-xs-1.text-center = check_box_tag 'q[id_eq_any][]', r.id, @select_ids.try(:fetch, 'id_eq_any').try(:fetch, i, false)
          .col-xs-2 = r.recording_number
          .col-xs-1 = r.try(:matured_on).try(:strftime, "%Y-%m-%d")
          .col-xs-1.text-right id="money#{r.id}" = number_to_currency(r.residual_money, unit: '', precision: 0)
          .col-xs-1.text-right = number_to_currency(r.issue_money, unit: '', precision: 0)
          .col-xs-2 = r.trader.try(:abbreviation)
          .col-xs-1 = r.try(:debtor_name)
          .col-xs-1 = r.try(:occurred_on).try(:strftime, "%Y-%m-%d")
          .col-xs-1 = r.try(:transferred_on).try(:strftime, "%Y-%m-%d")
      .row
       actions.col-xs-12
        = button_tag '全選択', type: :button, id: :check_all, class: 'btn btn-default col-xs-1'
        = button_tag '全解除', type: :button, id: :cancel_all, class: 'btn btn-default col-xs-1 col-xs-offset-1'
        = submit_tag '次へ', id: :transfer_select_button, class: 'btn btn-primary col-xs-2 col-xs-offset-6', disabled: true

app/views/receivables/transfers/search.html.slim
= render :partial => 'shared/receivables/stage'
section.container
  .row
    = form_tag select_receivables_transfers_path, method: :get do
      = submit_tag '戻る', name: :back, class: "btn btn-default col-xs-2 pull-right back-button"
  = search_form_for @q, url: result_receivables_transfers_path, method: :get do |f|
    div
      = render partial: "search_information"
      .search_container
        .row
          .col-xs-2
            label = "処理選択"
          .col-xs-2
            = f.radio_button :state_code_id_eq, StateCode.where(division: 1, ebill: '発生').pluck(:code).first, checked: true
            = f.label :state_code_id_eq, "譲渡処理", value: StateCode.where(division: 1, ebill: '発生').pluck(:code).first
          .col-xs-8
            = f.radio_button :state_code_id_eq, StateCode.where(division: 1, ebill: '譲渡').pluck(:code).first
            = f.label :state_code_id_eq, "譲渡取消", value: StateCode.where(division: 1, ebill: '割引').pluck(:code).first

        .row
          .col-xs-2
            label = "集計範囲"
          .col-xs-2
            = select_tag :period_type_1, options_for_select(Settings.enumerize_options.receivables.period_types.map{|h| [t(h.name), h.id]}, selected: @aggregate_scope.try(:fetch, 'period_type_1', 1).to_i)
          .col-xs-8
            = search_field_tag :period_1_from, @aggregate_scope.try(:fetch, 'period_1_from', nil), disabled: true, class: :inputCalendars, autocomplete: :off
            span.margin_lr ～
            = search_field_tag :period_1_to, @aggregate_scope.try(:fetch, 'period_1_to', nil), disabled: true, class: :inputCalendars, autocomplete: :off
        .row
          .col-xs-2.col-xs-offset-2
            =  select_tag :period_type_2, options_for_select(Settings.enumerize_options.receivables.period_types.map{|h| [t(h.name), h.id]}, selected: @aggregate_scope.try(:fetch, 'period_type_2', 1).to_i)
          .col-xs-8
            = search_field_tag :period_2_from, @aggregate_scope.try(:fetch, 'period_2_from', nil), disabled: true, class: :inputCalendars, autocomplete: :off
            span.margin_lr ～
            = search_field_tag :period_2_to, @aggregate_scope.try(:fetch, 'period_2_to', nil), disabled: true, class: :inputCalendars, autocomplete: :off
        .row
          .col-xs-2.col-xs-offset-2
            = f.label :traders_code
          .col-xs-8
            = f.search_field :trader_id_gteq
            span.margin_lr ～
            = f.search_field :trader_id_lteq
        .row
          .col-xs-2.col-xs-offset-2
            = f.label :residual_money
          .col-xs-8
            = f.search_field :residual_money_gteq
            span.margin_lr ～
            = f.search_field :residual_money_lteq
        .row
          .col-xs-2
            = f.label :transfer_date
          .col-xs-10
            = f.search_field :transferred_on_gteq, disabled: true, class: :inputCalendars, autocomplete: :off
            span.margin_lr ～
            = f.search_field :transferred_on_lteq, disabled: true, class: :inputCalendars, autocomplete: :off
        .row
          .col-xs-2
            = f.label :transferee_code
          .col-xs-10
            = f.search_field :transferee_trader_id_gteq, disabled: true
            span.margin_lr ～
            = f.search_field :transferee_trader_id_lteq, disabled: true
    div
      .row
       actions.col-xs-12
        = button_tag 'キャンセル', id: :search_cancel, type: 'button', class: 'btn btn-primary col-xs-2 col-xs-offset-6'
        = f.submit '次へ', id: :search_submit, class: 'btn btn-primary col-xs-2 col-xs-offset-1'

app/views/receivables/transfers/select.html.slim
= render :partial => 'shared/receivables/stage'
= nested_form_for @instance, :url => { action: :search } do |f|
  section.select_container
    .row
      = link_to '戻る', receivables_dealing_choice_transfers_path, class: "btn btn-default col-xs-2 pull-right back-button"
    .dtable
      dl
        dt = f.label :recording_institution_id
        dd = f.collection_select :recording_institution_id, RecordingInstitution.where(code: Settings.enumerize_options.receivables.recording_institutions.code.densai), :code, :name
      dl
        dt = f.label :company_bank_id
        dd = f.text_field :company_bank_id

    .dtable
      dl
        dt = f.label :transferred_on
        dd = f.text_field :transferred_on, class: :inputCalendars, autocomplete: :off

    .dtable
      dl
        dt
          label 譲渡先指定
        dd
          .row
            .col-xs-4
              = check_box_tag :company_banks, autocomplete: :off
              small 自社譲渡を行う
            .col-xs-2.own_transfer_bank
              label 自社譲渡銀行
            .col-xs-6.killpadding
            = f.fields_for :company_bank do |f_company_bank| 
              = f_company_bank.text_field :code, disabled: true

    .dtable
      = f.fields_for :trader do |f_trader| 
        .row.dtable.killmargin.killborder
          dl.row-same-height
            dt.col-xs-height.col-full-height
              label 譲渡先情報
            dd.col-xs-height.col-full-height.killpadding
              .dtable2
                dl
                  dd
                    .row
                      = f_trader.text_field :code, :data => {toggle: :tooltip, placement: :top}, title: @instance.trader.code, class: 'col-xs-2'
                      label.radio-inline.col-xs-4
                        = radio_button_tag :transferee_code_use, 0, :checked => true
                        small 譲渡先コードを入力する
                      label.radio-inline.col-xs-4
                        = radio_button_tag :transferee_code_use, 1
                        small 譲渡先を手入力する
                = render partial: "transferee_information", locals: {f_trader: f_trader}
      dl
        dt = f.label :guaranteed
        dd
          label.radio-inline.rabel_height
            = f.radio_button :guaranteed, 0, :checked => true
            small なし
          label.radio-inline.rabel_height
            = f.radio_button :guaranteed, 1
            small 金融機関のみ

    .row.tail_button_area
      = f.button 'キャンセル', id: :select_cancel, type: :button, class: "btn btn-primary col-xs-2 col-xs-offset-2"
      = f.submit '次へ', id: :select_submit, class: "btn btn-primary col-xs-2 col-xs-offset-2", :disabled => true