config/routes.rb
# -*- coding: utf-8 -*-
Rails.application.routes.draw do

  devise_for :users, :path => "/", :skip => [:confirmations],
    :controllers => {:sessions => "sessions", :passwords => "passwords", :registrations => "registrations", :sign_up => 'no_sign_up',},
    :path_names => {:sign_in => 'login', :sign_out => 'logout', :registration => "profile"}

  root :to => 'tops#show'
  resource :top, :only => [:show]

  get  'operative_settings/control_panel', to: 'operative_settings#control_panel'
  post 'operative_settings/control_panel', to: 'operative_settings#control_panel'

  resource :security_policy, :except => [:destroy] do
    post :change_status, :on => :member
  end
  resource :accounts_setting, :except => [:destroy] do
    post :change_status, :on => :member
  end

  get '/company_banks/search_bank', to: 'company_banks#search_bank'
  get '/company_banks/search_branch', to: 'company_banks#search_branch'
  resources :company_banks

  resource :date_bank_payment
  resource :date_bank_settlement
  resource :payment_notice

  resources :receivables do
    get :search_bank, on: :collection
    get :search_branch, on: :collection
    get :make_modal, on: :collection
    get :search, on: :collection
    get :result, on: :collection
  end
  namespace :receivables do
    resources :settlements do
      get :search, on: :collection
      get :result, on: :collection
      post :select, on: :collection
      post :confirm, on: :collection
      post :update_all, on: :collection
    end
  end
  # FIXME: 検索にreceivableを利用するようになれば削除
  resources :receivable_searches, :only => [:index]

  namespace :receivables do
    resources :discounts do
      get :search, on: :collection
      get :result, on: :collection
      post :select, on: :collection
      post :confirm, on: :collection
      post :update_all, on: :collection
    end
    resources :transfers do
      get :select, on: :collection
      post :search, on: :collection
      get :result, on: :collection
      post :confirm, on: :collection
      post :update_all, on: :collection
      get :trader_search, on: :collection
      get :company_bank_search, on: :collection
    end
    get "dealing_choice/regist", :to => "dealing_choice#regist"
    get "dealing_choice/discounts", :to => "dealing_choice#discounts"
    get "dealing_choice/transfers", :to => "dealing_choice#transfers"
  end

  namespace :journals do
    resources :dealing_choice do
      get :select, on: :collection
    end
    resources :journal_data do
      get :search, on: :collection
      get :confirm, on: :collection
      post :output, on: :collection
    end
  end

  resources :payables
  resources :departments
  resources :approval_settings, :except => [:destroy, :create]
  resources :remarks
  resources :users
  resources :license_allotments
  resources :abridgments
  resources :management_items
  get '/menu_authorities/menu_option_collections'
  resources :menu_authorities
  get '/approvers/menu_collection'

  resources :approvers
  resources :traders do
    get :edit_or_delete, on: :collection
    get :site, on: :collection
    get :search, on: :collection
  end
  resources :traders
  resources :slip_divisions
  resources :accounts
  resources :sub_accounts
  resources :analysis_divisions
  resources :analysis_items
  resources :operating_divisions
  resources :operating_division_settings
  resources :operating_items
  resources :receipts
  resources :date_bank_spreadsheets

  get 'default_payable_sites/make_trader_site_modal', to: 'default_payable_sites#make_trader_site_modal'
  get  'default_payable_sites', to: 'default_payable_sites#index'
  post 'default_payable_sites', to: 'default_payable_sites#update'

  get 'date_bank_choice', to: 'date_bank_choice#index'

  resources :use_accounts

  namespace :admin do
    devise_for :administrators, :path => "/", :skip => [:confirmations],
      :path_names => {:sign_in => 'login', :sign_out => 'logout', :registration => "profile", :sign_up => 'no_sign_up'}

    root :to => 'tops#show'
    resource :top, only: [:show]
    resources :products
    resources :management_divisions
    resources :companies do
      resource :user
      resources :licenses
    end
    resources :recording_institutions
    resources :banks, only: [:new, :create]
    get '/financial_institutions', :to => 'financial_institutions#index'
    post '/financial_institutions/import', :to => 'financial_institutions#import'
    resource  :banks
    resources :branches
    resources :menus
    resources :state_codes
    resources :administrators
    resources :recording_institutions
    resources :business_divisions
    resources :bank_holidays
    resources :stamp_taxes
    resources :tax_divisions
    resources :tax_rates
    resources :infos
  end

end

app/controllers/journals/dealing_choice_controller.rb
class Journals::DealingChoiceController < BaseController
  def select
  end
end

app/controllers/journals/journal_data_controller.rb
class Journals::JournalDataController < BaseController
  def search
    @q = SlipHeader.search
  end
  def confirm
    @q = SlipHeader.search(search_params)
    @result = @q.result(distinct: true)
  end

  private
  def search_params
    submit_params = params.require(:q).permit(
      :journalizing_slip_date_gteq,
      :journalizing_slip_date_lteq,
      :bill_data_type_eq,
      :slip_detail_trader_code_gteq,
      :slip_detail_trader_code_lteq,
      :bill_ebill_receivable_states_trader_id_gteq,
      :slip_detail_trader_code_lteq
    )
  end
end

app/helpers/journals/dealing_choice_helper.rb
module Journals::DealingChoiceHelper
end

app/helpers/journals/journal_data_helper.rb
module Journals::JournalDataHelper
end

app/views/journals/journal_data/confirm.html.slim
= render :partial => 'shared/journals/stage'
section.container
  .row
    = form_tag search_journals_journal_data_path, method: :get do
      = submit_tag '戻る', name: :back, class: "btn btn-default col-xs-2 pull-right back-button"
  .confirm_container
    .row.col-xs-10.text-center
      .col-xs-1 作成指示
      .col-xs-1 管理番号
      .col-xs-1 てん末
      .col-xs-1 仕訳日付
      .col-xs-1 伝票番号
      .col-xs-2 借方勘定科目
      .col-xs-2 貸方勘定科目
      .col-xs-1 金額
      .col-xs-1 摘要
      .col-xs-1 行数
    .row.col-xs-2

    = search_form_for @q, url: output_journals_journal_data_path, method: :post do |f|
      - @result.each_with_index do |r, i|
        .row.col-xs-10.text-center
          .col-xs-1.text-center = check_box_tag 'q[id_eq_any][]', nil
          .col-xs-1 = r.ebill.control_number
          .col-xs-1 = r.ebill.state_code.bill
          .col-xs-1 = r.journalizing_slip_date.try(:strftime, "%Y-%m-%d")
          .col-xs-1 = r.slip_number
          .col-xs-2 = r.slip_detail.to_a.pop.balanced == '0' ? r.slip_detail.to_a.pop.account_name : nil
          .col-xs-2 = r.slip_detail.to_a.pop.balanced == '1' ? r.slip_detail.to_a.pop.account_name : nil
          .col-xs-1.text-right = number_to_currency(r.ebill_receivable_state.amount_money, unit: '', precision: 0)
          .col-xs-1 = r.slip_detail.to_a.pop.abridgment
          .col-xs-1 = r.details_linage
        .row.col-xs-2.text-center
          = link_to '仕訳確認', '#', class: 'btn btn-default'
      .row
        actions.col-xs-12
          = button_tag '全選択', type: :button, id: :check_all, class: 'btn btn-default col-xs-1'
          = button_tag '全解除', type: :button, id: :cancel_all, class: 'btn btn-default col-xs-1 col-xs-offset-1'
      .row
        actions.col-xs-12
          = button_tag 'リスト印刷', type: :button, id: :list_output_button, class: 'btn btn-default col-xs-2 col-xs-offset-7'
          = submit_tag '登録して出力画面へ', id: :journal_output_button, class: 'btn btn-primary col-xs-2 pull-right', disabled: true

app/views/journals/journal_data/output.html.slim
= render :partial => 'shared/journals/stage'
section.container
  .row
    = form_tag confirm_journals_journal_data_path, method: :get do
      = submit_tag '戻る', name: :back, class: "btn btn-default col-xs-2 pull-right back-button"

app/views/journals/journal_data/search.html.slim
= render :partial => 'shared/journals/stage'
section.container.search_container
  .row
    = form_tag select_journals_dealing_choice_index_path, method: :get do
      = submit_tag '戻る', name: :back, class: "btn btn-default col-xs-2 pull-right back-button"
  = search_form_for @q, url: confirm_journals_journal_data_path, method: :get do |f|
    .row
      .col-xs-2
        label = "仕訳日付"
      .col-xs-10
        = f.text_field :journalizing_slip_date_gteq, class: :inputCalendars, autocomplete: :off
        span.margin_lr ～
        = f.text_field :journalizing_slip_date_lteq, class: :inputCalendars, autocomplete: :off
    .row
      .col-xs-2
        label = "債権種別"
      .col-xs-10
        = f.select :ebill_data_type_eq, Settings.enumerize_options.journals.data_type.receivable.map { |item| [t(item.name), item.id] }, :prompt => "指定なし"
    .row
      .col-xs-2
        label = "てん末"
      .col-xs-10
        - Settings.enumerize_options.journals.facts.receivable.each do |fact|
          label
            = check_box_tag 'facts[id][]', fact[:id]
            = label_tag t(fact[:name]), nil
        = f.collection_select :ebill_receivable_state_own_state_id_eq, OwnState.where(company_id: current_user.company_id), :code, :name, {:prompt => "指定なし"}, {:disabled => true}

    .row
      .col-xs-2
        label = "取引先"
      .col-xs-10
        = f.text_field :slip_detail_trader_code_gteq, autocomplete: :off
        span.margin_lr ～
        = f.text_field :slip_detail_trader_code_lteq, autocomplete: :off
    .row
      .col-xs-2
        label = "自社取引銀行"
      .col-xs-10
        = f.text_field :ebill_receivable_state_trader_id_gteq, autocomplete: :off
        span.margin_lr ～
        = f.text_field :slip_detail_trader_code_lteq, autocomplete: :off

    .row
      .col-xs-2
        label = "利用者情報"
      .col-xs-10
        = f.text_field :renew_user_id_gteq, autocomplete: :off
        span.margin_lr ～
        = f.text_field :renew_user_id_lteq, autocomplete: :off

    .row
      .col-xs-2
        label = "出力区分"
      .col-xs-10
        / TODO: 未作成のransackタグを作成
        = f.label :exported, '未出力'
        = f.radio_button :exported_eq, 0, checked: true
        = f.label :exported, '出力済'
        = f.radio_button :exported_eq, 1

    .row
      actions.col-xs-12
        = submit_tag 'キャンセル', id: 'cancel', type: 'button', class: 'btn btn-primary col-xs-2'
        = f.submit '次へ', class: 'btn btn-primary col-xs-2 col-xs-offset-1'