config/routes.rb
# -*- coding: utf-8 -*-
Rails.application.routes.draw do

  devise_for :users, :path => "/", :skip => [:confirmations],
    :controllers => {:sessions => "sessions", :passwords => "passwords", :registrations => "registrations", :sign_up => 'no_sign_up',},
    :path_names => {:sign_in => 'login', :sign_out => 'logout', :registration => "profile"}

  root :to => 'tops#show'
  resource :top, :only => [:show]

  get  'operative_settings/control_panel', to: 'operative_settings#control_panel'
  post 'operative_settings/control_panel', to: 'operative_settings#control_panel'

  resource :security_policy, :except => [:destroy] do
    post :change_status, :on => :member
  end
  resource :accounts_setting, :except => [:destroy] do
    post :change_status, :on => :member
  end

  get '/company_banks/search_bank', to: 'company_banks#search_bank'
  get '/company_banks/search_branch', to: 'company_banks#search_branch'
  resources :company_banks

  resource :date_bank_payment
  resource :date_bank_settlement
  resource :payment_notice

  resources :receivables do
    get :search_bank, on: :collection
    get :search_branch, on: :collection
    get :make_modal, on: :collection
    get :search, on: :collection
    get :result, on: :collection
  end
  namespace :receivables do
    resources :settlements do
      get :search, on: :collection
      get :result, on: :collection
      post :select, on: :collection
      post :confirm, on: :collection
      post :update_all, on: :collection
    end
  end
  # FIXME: 検索にreceivableを利用するようになれば削除
  resources :receivable_searches, :only => [:index]

  namespace :receivables do
    resources :discounts do
      get :search, on: :collection
      get :result, on: :collection
      post :select, on: :collection
      post :confirm, on: :collection
      post :update_all, on: :collection
    end
    resources :transfers do
      get :select, on: :collection
      post :search, on: :collection
      get :result, on: :collection
      post :confirm, on: :collection
      post :update_all, on: :collection
      get :trader_search, on: :collection
      get :company_bank_search, on: :collection
    end
    get "dealing_choice/regist", :to => "dealing_choice#regist"
    get "dealing_choice/discounts", :to => "dealing_choice#discounts"
    get "dealing_choice/transfers", :to => "dealing_choice#transfers"
  end

  namespace :journals do
    resources :dealing_choice do
      get :select, on: :collection
    end
    resources :journal_data do
      get :search, on: :collection
      get :confirm, on: :collection
      post :output, on: :collection
    end
  end

  resources :payables
  resources :departments
  resources :approval_settings, :except => [:destroy, :create]
  resources :remarks
  resources :users
  resources :license_allotments
  resources :abridgments
  resources :management_items
  get '/menu_authorities/menu_option_collections'
  resources :menu_authorities
  get '/approvers/menu_collection'

  resources :approvers
  resources :traders do
    get :edit_or_delete, on: :collection
    get :site, on: :collection
    get :search, on: :collection
  end
  resources :traders
  resources :slip_divisions
  resources :accounts
  resources :sub_accounts
  resources :analysis_divisions
  resources :analysis_items
  resources :operating_divisions
  resources :operating_division_settings
  resources :operating_items
  resources :receipts
  resources :date_bank_spreadsheets

  get 'default_payable_sites/make_trader_site_modal', to: 'default_payable_sites#make_trader_site_modal'
  get  'default_payable_sites', to: 'default_payable_sites#index'
  post 'default_payable_sites', to: 'default_payable_sites#update'

  get 'date_bank_choice', to: 'date_bank_choice#index'

  resources :use_accounts

  namespace :admin do
    devise_for :administrators, :path => "/", :skip => [:confirmations],
      :path_names => {:sign_in => 'login', :sign_out => 'logout', :registration => "profile", :sign_up => 'no_sign_up'}

    root :to => 'tops#show'
    resource :top, only: [:show]
    resources :products
    resources :management_divisions
    resources :companies do
      resource :user
      resources :licenses
    end
    resources :recording_institutions
    resources :banks, only: [:new, :create]
    get '/financial_institutions', :to => 'financial_institutions#index'
    post '/financial_institutions/import', :to => 'financial_institutions#import'
    resource  :banks
    resources :branches
    resources :menus
    resources :state_codes
    resources :administrators
    resources :recording_institutions
    resources :business_divisions
    resources :bank_holidays
    resources :stamp_taxes
    resources :tax_divisions
    resources :tax_rates
    resources :infos
  end

end

app/models/accounts_setting.rb
class AccountsSetting < ActiveRecord::Base
  extend Enumerize
  acts_as_paranoid
  
  enumerize :abridgment_method, in:  Settings.enumerize_options.abridgment_method
  enumerize :payment_type, in:  Settings.enumerize_options.payment_type
end

app/controllers/accounts_settings_controller.rb
class AccountsSettingsController < BaseController
  permit_attributes :endorsement_ac_used, :discount_ac_used, :abridgment_method, :remarks1_reflected, :remarks2_reflected, 
                    :remarks3_reflected, :payment_type, :notice_journal_made
  
  before_action :create_accounts_setting
  before_action :load_object
  
  def load_object
    instance_variable_set \
      "@#{model_name.underscore}",
      (@instance = model.find_by_company_id(current_user.company_id) rescue nil).tap { |instance| instance.try(:assign_attributes, permitted_parameters) }
  end

  def redirect_path
    accounts_setting_path
  end
  
  def create_accounts_setting
    unless model.find_by_company_id(@my_company.id)
      AccountsSetting.create(
        company_id: @my_company.id,
        endorsement_ac_used: false, 
        discount_ac_used: false, 
        abridgment_method: "line", 
        remarks1_reflected: false, 
        remarks2_reflected: false, 
        remarks3_reflected: false, 
        payment_type: "no_payment", 
        notice_journal_made: false
      )
    end
  end
end

app/helpers/accounts_settings_helper.rb
module AccountsSettingsHelper
end

app/views/accounts_settings/_form.html.slim
.row
  .col-md-6 
    div class='box box-primary'
      .box-body
        = form_for(object, url: accounts_setting_path, :html => {:class => "form-horizontal"}, method: (object.new_record? ? :post : :put)) do |f|
          = render partial: 'shared/errors', locals: {errors: object.errors}
          
          div align="right"
            = link_to t('.back'), accounts_setting_path
          br

          .form-group
            = f.label :endorsement_ac_used, class: 'col-xs-3 form-control-static'
            .col-xs-9
              = f.radio_button :endorsement_ac_used, true, {}
              = t('accounts_settings.endorsement_ac_used.use')
              = f.radio_button :endorsement_ac_used, false, {}
              = t('accounts_settings.endorsement_ac_used.not_use')

          .form-group
            = f.label :discount_ac_used, class: 'col-xs-3 form-control-static'
            .col-xs-9
              = f.radio_button :discount_ac_used, true, {}
              = t('accounts_settings.discount_ac_used.use')
              = f.radio_button :discount_ac_used, false, {}
              = t('accounts_settings.discount_ac_used.not_use')

          .form-group
            = f.label :abridgment_method, class: 'col-xs-3 form-control-static'
            .col-xs-9
              = f.select :abridgment_method, AccountsSetting.abridgment_method.options, {}, class: 'form-control'

          .form-group
            = f.label :remarks1_reflected, class: 'col-xs-3 form-control-static'
            .col-xs-9
              = f.radio_button :remarks1_reflected, true, {}
              = t('accounts_settings.remarks1_reflected.display')
              = f.radio_button :remarks1_reflected, false, {}
              = t('accounts_settings.remarks1_reflected.not_display')

          .form-group
            = f.label :remarks2_reflected, class: 'col-xs-3 form-control-static'
            .col-xs-9
              = f.radio_button :remarks2_reflected, true, {}
              = t('accounts_settings.remarks2_reflected.display')
              = f.radio_button :remarks2_reflected, false, {}
              = t('accounts_settings.remarks2_reflected.not_display')

          .form-group
            = f.label :remarks3_reflected, class: 'col-xs-3 form-control-static'
            .col-xs-9
              = f.radio_button :remarks3_reflected, true, {}
              = t('accounts_settings.remarks3_reflected.display')
              = f.radio_button :remarks3_reflected, false, {}
              = t('accounts_settings.remarks3_reflected.not_display')

          .form-group
            = f.label :abridgment_method, class: 'col-xs-3 form-control-static'
            .col-xs-9
              = f.select :payment_type, AccountsSetting.payment_type.options, {}, class: 'form-control'

          .form-group
            = f.label :notice_journal_made, class: 'col-xs-3 form-control-static'
            .col-xs-9
              = f.radio_button :notice_journal_made, true, {}
              = t('accounts_settings.notice_journal_made.use')
              = f.radio_button :notice_journal_made, false, {}
              = t('accounts_settings.notice_journal_made.not_use')

          div align="right"
            = f.submit t(object.new_record? ? '.create' : '.update'), class: 'btn btn-primary'
          br





              

app/views/accounts_settings/_item.html.slim
.row
  .col-md-6 
    div class='box box-primary'
      .box-body
      
      div align="left"
        =button_link_to t('general.label.edit'), edit_accounts_setting_path
      br

      - @accounts_setting.tap do |item|
        - %w(endorsement_ac_used discount_ac_used).each do |attr|
          .form-group
            = AccountsSetting.human_attribute_name(attr)
            br
            = t("accounts_settings.#{attr}.#{item.read_attribute(attr) ? 'use' : 'not_use'}")

        .form-group
          = AccountsSetting.human_attribute_name(:abridgment_method)
          br
          = t("accounts_settings.abridgment_method.#{item.abridgment_method}")

        -  %w(remarks1_reflected remarks2_reflected remarks3_reflected).each do |attr|
          .form-group
            = AccountsSetting.human_attribute_name(attr)
            br
            = t("accounts_settings.#{attr}.#{item.read_attribute(attr) ? 'display' : 'not_display'}")

        .form-group
          = AccountsSetting.human_attribute_name(:payment_type)
          br
          = t("accounts_settings.payment_type.#{item.payment_type}")

        - %w(notice_journal_made).each do |attr|
          .form-group
            = AccountsSetting.human_attribute_name(attr)
            br
            = t("accounts_settings.#{attr}.#{item.read_attribute(attr) ? 'use' : 'not_use'}")
          br